#!/bin/bash
# backup-wazuh-stack.sh
#
# Nightly backup of the Wazuh stack (manager + indexer + dashboard) state
# on manager-host (192.0.2.106). Designed to run from a daily cron at 03:00 UTC
# so a complete restore is possible if manager-host dies.
#
# What gets backed up:
#   1. /home/user/wazuh-stack/                 (compose + all configs)
#   2. /home/user/.openclaw/workspace/secrets/  (Wazuh API + agent keys)
#   3. /home/user/wazuh-stack/wazuh-certificates/  (legacy cert dir)
#   4. Wazuh indexer data via docker exec (alert indices, .opendistro_security,
#      the rotated internal_users hash, templates) - tarred directly from
#      the container's /var/lib/wazuh-indexer
#   5. /etc/systemd/system/wazuh-* units (manager-restart helper etc.)
#
# Where it goes:
#   /home/user/wazuh-stack-backups/YYYY-MM-DD/
#   └── wazuh-stack-YYYY-MM-DD.tar.zst   (everything from items 1-4, ~150M)
#   └── INDEX                              (sha256 + sizes + contents list)
#   └── RESTORE.md                         (recovery procedure)
#
# Retention: 30 days. Backups older than 30 days are removed.
#
# Recovery: see /home/user/wazuh-stack-backups/RESTORE.md (generated by this
# script) or docs/soc/wazuh-stack-disaster-recovery.md (the long-form runbook).
#
# Cron: 0 3 * * * /home/user/.openclaw/workspace/agentic-ai/ops/backup-wazuh.sh
# Exit codes:
#   0 = backup succeeded, INDEX written
#   1 = docker not available
#   2 = one or more backup sources missing (warns but doesn't fail)
#   3 = tar/zstd failed
#   4 = INDEX write failed
#   5 = BOTH indexer + manager container state missing (silent-failure guard)

set -euo pipefail

# log/bail helpers must be defined before the auto-detect block
# (which uses `log` to report detected container names).
log() { echo "[$(date -u +%FT%TZ)] $*" | tee -a "$LOG" >&2; }
bail() { log "ERROR: $*"; exit "${2:-1}"; }

# Configuration
BACKUP_ROOT="${BACKUP_ROOT:-/home/user/wazuh-stack-backups}"
DATE=$(date -u +%Y-%m-%d)
TIMESTAMP=$(date -u +%Y%m%dT%H%M%SZ)
BACKUP_DIR="$BACKUP_ROOT/$DATE"
ARCHIVE="$BACKUP_DIR/wazuh-stack-$TIMESTAMP.tar.zst"
INDEX="$BACKUP_DIR/INDEX"
LOG="${LOG:-/home/user/wazuh-stack-backups/backup.log}"
KEEP_DAYS="${KEEP_DAYS:-30}"

# Container names: auto-detect from docker if not set explicitly.
# Compose v2 names with hyphens (e.g. wazuh-stack-wazuh.manager-1);
# compose v1 / legacy stacks use underscores + dots
# (e.g. wazuh-stack_wazuh.manager_1). Resolve once up-front so the
# rest of the script can rely on a single canonical name.
DOCKER_PROJECT="${DOCKER_PROJECT:-wazuh-stack}"
detect_container() {
  local svc="$1" hint="$2"
  local found
  found=$(docker ps --format '{{.Names}}' \
    | grep -E "^${DOCKER_PROJECT}[-_]${svc}[-_]1$" \
    | head -1)
  if [ -z "$found" ]; then
    log "  ! no running container matching ${DOCKER_PROJECT}[-_]${svc}[-_]1 (skipping)"
    echo ""
    return
  fi
  log "  detected ${svc} container: $found (hint was $hint)"
  echo "$found"
}

INDEXER_CONTAINER="${INDEXER_CONTAINER:-$(detect_container wazuh.indexer wazuh-stack_wazuh.indexer_1)}"
MANAGER_CONTAINER="${MANAGER_CONTAINER:-$(detect_container wazuh.manager wazuh-stack_wazuh.manager_1)}"
DASHBOARD_CONTAINER="${DASHBOARD_CONTAINER:-$(detect_container wazuh.dashboard wazuh-stack_wazuh.dashboard_1)}"

# Source paths to back up
HOST_SOURCES=(
  "/home/user/wazuh-stack"
  "/home/user/.openclaw/workspace/secrets/wazuh-agent-keys-2026-08-03.env"
  "/home/user/wazuh-stack/wazuh-certificates"
  "/etc/systemd/system/wazuh-manager-restart.service"
  "/etc/systemd/system/wazuh-daily-report.service"
  "/etc/systemd/system/wazuh-daily-report.timer"
  "/home/user/bin/wazuh-morning-highlights.sh"
  "/home/user/bin/wazuh-daily-digest.sh"
  "/home/user/bin/wazuh-stack"
  "/home/user/.openclaw/workspace/agentic-ai"
  "/home/user/repos/agentic-ai/scripts/wazuh-integrations"
  "/home/user/repos/agentic-ai/docs/infrastructure/wazuh-indexer-auth-pipeline.md"
  "/home/user/.openclaw/workspace/runbooks/wazuh-indexer-auth-pipeline.md"
)

command -v docker >/dev/null 2>&1 || bail "docker not on PATH" 1
command -v zstd >/dev/null 2>&1 || bail "zstd not on PATH" 1
mkdir -p "$BACKUP_DIR" || bail "cannot create $BACKUP_DIR" 1

log "=== Wazuh stack backup starting ==="
log "Target: $ARCHIVE"

# Build tar arguments, skipping missing sources (warn but don't fail)
TAR_ARGS=()
MISSING=()
for src in "${HOST_SOURCES[@]}"; do
  if [ -e "$src" ]; then
    TAR_ARGS+=("$src")
  else
    MISSING+=("$src")
    log "  ! missing source: $src (skipping)"
  fi
done

if [ ${#MISSING[@]} -gt 0 ]; then
  log "  ${#MISSING[@]} source(s) missing — backup will proceed without them"
fi

# Pull the indexer data via python tarfile. The wazuh-indexer container is
# a minimal RPM image with no `tar` binary, so we use python's tarfile
# module to stream /var/lib/wazuh-indexer as a tarball. We then EXTRACT
# that tarball on the host (under a working dir) so the final archive
# contains the indexer files in their natural path layout, not as a nested
# tarball.
log "Tarring indexer data from container $INDEXER_CONTAINER (via python tarfile)"
INDEXER_RAW=$(mktemp /tmp/wazuh-indexer-raw-XXXXXX.tar)
INDEXER_EXTRACT=$(mktemp -d /tmp/wazuh-indexer-extract-XXXXXX)
trap 'rm -rf "$INDEXER_RAW" "$INDEXER_EXTRACT"' EXIT
docker exec "$INDEXER_CONTAINER" python3 -c "
import tarfile, sys, os
buf = sys.stdout.buffer
with tarfile.open(fileobj=buf, mode='w|') as tf:
    for root, dirs, files in os.walk('/var/lib/wazuh-indexer'):
        for f in files:
            p = os.path.join(root, f)
            try:
                tf.add(p)
            except Exception as e:
                print('skip', p, e, file=sys.stderr)
" > "$INDEXER_RAW" 2>/dev/null \
  || { log "  ! failed to tar indexer data (non-fatal)"; INDEXER_RAW=""; }
if [ -n "$INDEXER_RAW" ] && [ -s "$INDEXER_RAW" ]; then
  tar -xf "$INDEXER_RAW" -C "$INDEXER_EXTRACT" 2>/dev/null \
    || log "  ! failed to extract indexer data on host (non-fatal)"
  INDEXER_SRC="$INDEXER_EXTRACT/var/lib/wazuh-indexer"
else
  INDEXER_SRC=""
fi

# Manager container has tar in $PATH (Ubuntu-based).
log "Tarring manager state from container $MANAGER_CONTAINER"
MGR_RAW=$(mktemp /tmp/wazuh-manager-raw-XXXXXX.tar)
MGR_EXTRACT=$(mktemp -d /tmp/wazuh-manager-extract-XXXXXX)
cleanup() {
  rm -rf "$INDEXER_RAW" "$INDEXER_EXTRACT" "$INDEXER_SRC" "$MGR_RAW" "$MGR_EXTRACT" 2>/dev/null || true
}
trap cleanup EXIT
docker exec "$MANAGER_CONTAINER" tar -cf - -C / var/ossec/etc 2>/dev/null > "$MGR_RAW" \
  || { log "  ! failed to tar manager state (non-fatal)"; MGR_RAW=""; }
if [ -n "$MGR_RAW" ] && [ -s "$MGR_RAW" ]; then
  tar -xf "$MGR_RAW" -C "$MGR_EXTRACT" 2>/dev/null \
    || log "  ! failed to extract manager state on host (non-fatal)"
  MGR_SRC="$MGR_EXTRACT/var/ossec/etc"
else
  MGR_SRC=""
fi

# Build the final archive. Some sources (e.g. /home/user/wazuh-stack/config/
# wazuh_indexer/internal_users.yml and the cert .key.pem files) are owned
# by user jdr (uid 1001) with mode 0600, so we need sudo -n to read them.
# manager-host has the standard demo-user NOPASSWD sudo rule for any tar invocation.
log "Compressing archive (using sudo -n tar for jdr-owned files)"

# Build the tar command line as a single string so we can pass it cleanly.
# The extracted indexer + manager data go in as their own top-level dirs
# (indexer-data/, manager-state/) so a restore can pick what to put back.
build_tar_command() {
  local cmd="tar -cf -"
  for src in "${TAR_ARGS[@]}"; do
    cmd+=" -C $(dirname "$src") $(basename "$src")"
  done
  if [ -n "$INDEXER_SRC" ] && [ -d "$INDEXER_SRC" ]; then
    cmd+=" -C $(dirname "$INDEXER_SRC") $(basename "$INDEXER_SRC")"
  fi
  if [ -n "$MGR_SRC" ] && [ -d "$MGR_SRC" ]; then
    cmd+=" -C $(dirname "$MGR_SRC") $(basename "$MGR_SRC")"
  fi
  echo "$cmd"
}
TAR_CMD=$(build_tar_command)

# shellcheck disable=SC2086
sudo -n bash -c "$TAR_CMD" | zstd -T0 -19 -o "$ARCHIVE" \
  || bail "tar/zstd failed" 3

# Verify the archive
[ -s "$ARCHIVE" ] || bail "archive is empty: $ARCHIVE" 3
ARCHIVE_SIZE=$(du -h "$ARCHIVE" | awk '{print $1}')
ARCHIVE_SHA=$(sha256sum "$ARCHIVE" | awk '{print $1}')
log "Archive: $ARCHIVE ($ARCHIVE_SIZE) sha256=$ARCHIVE_SHA"

# Silent-failure guard: if NEITHER the indexer NOR the manager container
# state was captured, the backup is useless for restoration. Hard-fail
# loudly so we notice immediately rather than discovering it post-mortem
# when the stack is already dead.
if [ -z "$INDEXER_SRC" ] && [ -z "$MGR_SRC" ]; then
  bail "BOTH indexer and manager container state are missing — backup would not be restorable" 5
fi
if [ -z "$INDEXER_SRC" ]; then
  log "  ⚠️  WARNING: indexer data not captured (cluster alerts + security config at risk)"
fi
if [ -z "$MGR_SRC" ]; then
  log "  ⚠️  WARNING: manager state not captured (rules + agent keys at risk)"
fi

# Write the INDEX
log "Writing INDEX"
INDEX_TMP=$(mktemp)
trap 'rm -f "$INDEX_TMP"' EXIT

cat > "$INDEX_TMP" <<EOF
Wazuh stack backup — $DATE
Generated: $TIMESTAMP

Archive:    $(basename "$ARCHIVE")
Location:   $ARCHIVE
Size:       $ARCHIVE_SIZE
Sha256:     $ARCHIVE_SHA
Compression: zstd level 19

Sources (host):
$(printf '  - %s\n' "${HOST_SOURCES[@]}")

Missing sources:
$(printf '  - %s\n' "${MISSING[@]:-(none)}")

Container data:
  indexer: $INDEXER_CONTAINER → /var/lib/wazuh-indexer (alert indices, templates, .opendistro_security)
  manager: $MANAGER_CONTAINER → /var/ossec/etc (rules, decoders, agent keys, certs)

Recovery: see $BACKUP_DIR/RESTORE.md
EOF

# Generate a recovery runbook alongside the backup
cat > "$BACKUP_DIR/RESTORE.md" <<EOF
# Wazuh stack recovery — backup $DATE

## What's in this backup

\`\`\`
$(ls -la "$BACKUP_DIR" | tail -n +2)
\`\`\`

## Quick restore on a fresh manager-host (Ubuntu 24.04)

\`\`\`bash
# 1. Reinstall Docker + compose
sudo apt-get install -y docker.io docker-compose-plugin

# 2. Restore the wazuh-stack config dir
sudo tar -C / --zstd -xf $ARCHIVE home/demo-user/wazuh-stack/

# 3. Restore secrets
sudo mkdir -p /home/user/.openclaw/workspace/secrets
sudo tar -C / --zstd -xf $ARCHIVE home/demo-user/.openclaw/workspace/secrets/

# 4. Restore systemd units + cron
sudo cp /home/user/wazuh-stack/systemd/wazuh-*.service /etc/systemd/system/ 2>/dev/null || true
sudo systemctl daemon-reload

# 5. Bring the stack back up
cd /home/user/wazuh-stack
docker compose up -d

# 6. Verify (see the long-form runbook for what to check)
curl -sS -k -u admin:\$INDEXER_PASSWORD https://localhost:9200/_cluster/health?pretty
\`\`\`

## Long-form recovery procedure

For the full disaster-recovery runbook (including the cert+internalusers
re-initialization that this backup captures), see:

  /home/user/repos/agentic-ai/docs/soc/wazuh-stack-disaster-recovery.md
EOF

mv "$INDEX_TMP" "$INDEX"
log "INDEX written: $INDEX"

# Cleanup the inner tarballs (they're now inside the .tar.zst)
# (no inner tarballs to clean up; they're now inside the .tar.zst)

# Retention: remove backups older than KEEP_DAYS
if [ -d "$BACKUP_ROOT" ]; then
  log "Pruning backups older than $KEEP_DAYS days"
  find "$BACKUP_ROOT" -maxdepth 1 -type d -name "20*-*-*" -mtime "+$KEEP_DAYS" -exec rm -rf {} \; \
    && log "  pruned" || log "  prune step had errors (non-fatal)"
fi

log "=== Backup complete: $ARCHIVE ($ARCHIVE_SIZE) ==="
exit 0
